# Generated by Django 4.2.4 on 2023-09-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('Description', models.CharField(max_length=255)),
                ('Reference', models.CharField(max_length=250)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountNumber', models.CharField(max_length=20, unique=True)),
                ('AccountName', models.CharField(max_length=255, unique=True)),
                ('AccountType', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoices',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TransalctionDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('Description', models.CharField(max_length=250)),
                ('Reference', models.CharField(max_length=250)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.BooleanField()),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=255, unique=True)),
                ('CustomerAddress', models.CharField(max_length=255)),
                ('ContactPerson', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMoney',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('Description', models.CharField(max_length=255)),
                ('Reference', models.CharField(max_length=250)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMoney',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('Description', models.CharField(max_length=255)),
                ('Reference', models.CharField(max_length=250)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=255, unique=True)),
                ('VendorAddress', models.CharField(max_length=255)),
                ('ContactPerson', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorBills',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TransalctionDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('Description', models.CharField(max_length=250)),
                ('Reference', models.CharField(max_length=250)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.BooleanField()),
                ('BillPaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.billpayments')),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
                ('VendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMoneyLines',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LineAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IncommingMoneyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.outgoingmoney')),
                ('LineCOA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
        migrations.AddField(
            model_name='outgoingmoney',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.vendors'),
        ),
        migrations.CreateModel(
            name='InvoicePayments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TransalctionDate', models.DateField()),
                ('Description', models.CharField(max_length=250)),
                ('Reference', models.CharField(max_length=250)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLines',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LineAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.customerinvoices')),
                ('LineCOA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMoneyLines',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LineAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IncommingMoneyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.incomingmoney')),
                ('LineCOA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoices',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.customers'),
        ),
        migrations.AddField(
            model_name='customerinvoices',
            name='InvoicePaymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.invoicepayments'),
        ),
        migrations.AddField(
            model_name='billpayments',
            name='COA_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts'),
        ),
        migrations.CreateModel(
            name='BillLines',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LineAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.vendorbills')),
                ('LineCOA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_and_finance_management.chartofaccounts')),
            ],
        ),
    ]
