# Generated by Django 4.2.4 on 2023-09-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('emergency_contact', models.CharField(max_length=250)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('position_start_date', models.DateField()),
                ('position_end_date', models.DateField(null=True)),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_data.employees')),
            ],
        ),
    ]
