# Generated by Django 4.2.6 on 2023-11-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people_data", "0002_rename_employees_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Positions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("position_title", models.CharField(max_length=100)),
                ("position_description", models.CharField(max_length=250)),
                ("position_tier", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shifts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("shift_name", models.CharField(max_length=100)),
                ("shift_description", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="HolidayRecords",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("date", models.DateField()),
                ("hours", models.IntegerField()),
                (
                    "employee_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_data.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HolidayAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("number_of_holiday_hours", models.IntegerField()),
                (
                    "employee_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_data.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsenceRecords",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("date", models.DateField()),
                ("hours", models.IntegerField()),
                ("reason", models.CharField(max_length=250)),
                ("business_choice", models.BooleanField()),
                ("authorised", models.BooleanField(null=True)),
                (
                    "employee_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_data.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employmenthistory",
            name="shift",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="people_data.shifts",
            ),
        ),
        migrations.AlterField(
            model_name="employmenthistory",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people_data.positions"
            ),
        ),
    ]
